# Generated by Django 5.0.6 on 2024-08-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0003_fcmnotification_fcmtokenmodel_delete_fcmdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmnotification',
            name='device_registration_token',
        ),
    ]
