# Generated by Django 5.0.6 on 2024-08-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0006_alter_fcmtokenmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmnotification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
