# Generated by Django 5.0.6 on 2024-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0007_alter_fcmnotification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmnotification',
            name='exchange_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
