# Generated by Django 5.0.6 on 2024-08-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0008_fcmnotification_exchange_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmnotification',
            name='exchange_payload',
        ),
    ]
