# Generated by Django 5.0.6 on 2024-08-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0011_alter_fcmtokenmodel_stale_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtokenmodel',
            name='stale_time',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('10m', '10 Minutes'), ('1', '1 Day'), ('3', '3 Days'), ('7', '1 Week'), ('14', '2 Weeks'), ('30', '1 Month'), ('90', '3 Months'), ('180', '6 Months'), ('365', '1 Year')], default='1', max_length=255),
        ),
    ]
