# Generated by Django 5.0.6 on 2024-08-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0012_alter_fcmtokenmodel_stale_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtokenmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fcmtokenmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
