# Generated by Django 5.0.6 on 2024-08-08 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm', '0013_fcmtokenmodel_created_at_fcmtokenmodel_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmnotification',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_notifications_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
