# Generated by Django 5.0.6 on 2024-07-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_verificationcode_code_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
