# Generated by Django 5.0.6 on 2024-07-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_customuser_llogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='code_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=5),
        ),
    ]
