# Generated by Django 5.0.6 on 2024-07-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_verificationcode_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='code_type',
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
