# Generated by Django 5.0.6 on 2024-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
