# Generated by Django 5.0.6 on 2024-07-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_customuser_phone_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreed_to_Terms',
            field=models.BooleanField(default=False),
        ),
    ]
