# Generated by Django 5.0.6 on 2024-07-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_azampayauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azampayauthtoken',
            name='expires_in',
        ),
        migrations.AlterField(
            model_name='azampayauthtoken',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azampayauthtoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azampayauthtoken',
            name='token_type',
            field=models.CharField(default='Bearer', max_length=255),
        ),
    ]
