# Generated by Django 5.0.6 on 2024-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_azampayauthtoken_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azampayauthtoken',
            name='token_type',
            field=models.CharField(blank=True, default='Bearer', max_length=255, null=True),
        ),
    ]
