# Generated by Django 5.0.6 on 2024-08-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
