# Generated by Django 5.0.6 on 2024-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('geust', 'Guest'), ('host', 'Host')], default='geust', max_length=255),
        ),
    ]
