# Generated by Django 5.0.6 on 2024-08-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
