# Generated by Django 5.0.6 on 2024-07-20 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_rename_order_completed_mypropertypurchase_canceled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypropertypurchasestatus',
            old_name='order_canceled',
            new_name='canceled',
        ),
        migrations.RenameField(
            model_name='mypropertypurchasestatus',
            old_name='order_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='mypropertypurchasestatus',
            old_name='order_confirmed',
            new_name='confirmed',
        ),
        migrations.RemoveField(
            model_name='mybookingpayment',
            name='payment_card',
        ),
        migrations.RemoveField(
            model_name='mypropertypurchase',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='mypropertypurchase',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='mypropertypurchase',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='mypropertypurchase',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='mypropertypurchase',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='mypropertypurchase',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='mypropertypurchasepayment',
            name='payment_card',
        ),
        migrations.RemoveField(
            model_name='myrentingpayment',
            name='payment_card',
        ),
        migrations.RemoveField(
            model_name='myrentingstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='myrentingstatus',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myrentingstatus',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myrentingstatus',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myrentingstatus',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myrentingstatus',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myrentingstatus',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MyBookingPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('payment_completed', models.BooleanField(default=False)),
                ('payment_canceled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('to_be_refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.mybookingpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=100)),
                ('mobile_holder_name', models.CharField(max_length=100)),
                ('mobile_network', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyPropertyPurchasePaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('to_be_refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_purchase_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.mypropertypurchasepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyRentingPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('payment_completed', models.BooleanField(default=False)),
                ('payment_canceled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('to_be_refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renting_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.myrentingpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('creditcard', 'Credit Card'), ('airtellmoney', 'Debit Card'), ('mpesa', 'Mpesa'), ('tigopesa', 'Tigo Pesa')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mybookingpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.paymentmethod'),
        ),
        migrations.AddField(
            model_name='mypropertypurchasepayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.paymentmethod'),
        ),
        migrations.AddField(
            model_name='myrentingpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.paymentmethod'),
        ),
    ]
