# Generated by Django 5.0.6 on 2024-07-22 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_rename_order_canceled_mypropertypurchasestatus_canceled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyMobileMoney',
            new_name='MyMobileMoneyPaymentinfos',
        ),
    ]
