# Generated by Django 5.0.6 on 2024-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0008_alter_mybookingpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybookingpayment',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='mypaymentcard',
            name='card_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
