# Generated by Django 5.0.6 on 2024-07-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0013_rename_card_number_mypaymentcard_acount_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypaymentcard',
            old_name='acount_number',
            new_name='account_number',
        ),
    ]
