# Generated by Django 5.0.6 on 2024-07-25 06:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_remove_propertyhostcancelationpolicy_host_and_more'),
        ('user_data', '0014_rename_acount_number_mypaymentcard_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mybookingpayment',
            unique_together={('user', 'booking')},
        ),
        migrations.AlterUniqueTogether(
            name='mybookingpaymentstatus',
            unique_together={('user', 'booking_payment')},
        ),
        migrations.AlterUniqueTogether(
            name='mybookingstatus',
            unique_together={('user', 'booking')},
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchase',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchasepayment',
            unique_together={('user', 'property_purchase')},
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchasepaymentstatus',
            unique_together={('user', 'property_purchase_payment')},
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchasestatus',
            unique_together={('user', 'property_purchase')},
        ),
        migrations.AlterUniqueTogether(
            name='myrenting',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='myrentingpayment',
            unique_together={('user', 'renting')},
        ),
        migrations.AlterUniqueTogether(
            name='myrentingpaymentstatus',
            unique_together={('user', 'renting_payment')},
        ),
        migrations.AlterUniqueTogether(
            name='myrentingstatus',
            unique_together={('user', 'renting')},
        ),
    ]
