# Generated by Django 5.0.6 on 2024-07-25 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_remove_propertyhostcancelationpolicy_host_and_more'),
        ('user_data', '0015_alter_mybookingpayment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myaddress',
            options={'verbose_name': '2 My Address', 'verbose_name_plural': '2 My Address'},
        ),
        migrations.AlterModelOptions(
            name='mybooking',
            options={'verbose_name': '5 My Booking', 'verbose_name_plural': '5 My Booking'},
        ),
        migrations.AlterModelOptions(
            name='mybookingpayment',
            options={'verbose_name': '7 My Booking Payment', 'verbose_name_plural': '7 My Booking Payment'},
        ),
        migrations.AlterModelOptions(
            name='mybookingpaymentstatus',
            options={'verbose_name': '8 My Booking Payment Status', 'verbose_name_plural': '8 My Booking Payment Status'},
        ),
        migrations.AlterModelOptions(
            name='mybookingstatus',
            options={'verbose_name': '6 My Booking Status', 'verbose_name_plural': '6 My Booking Status'},
        ),
        migrations.AlterModelOptions(
            name='myfavoriteproperty',
            options={'verbose_name': '1 My Favorite Property', 'verbose_name_plural': '1 My Favorite Property'},
        ),
        migrations.AlterModelOptions(
            name='mymobilemoneypaymentinfos',
            options={'verbose_name': '4 My Mobile Money Payment Infos', 'verbose_name_plural': '4 My Mobile Money Payment Infos'},
        ),
        migrations.AlterModelOptions(
            name='mypaymentcard',
            options={'verbose_name': '3 My Payment Card', 'verbose_name_plural': '3 My Payment Card'},
        ),
        migrations.AlterModelOptions(
            name='mypropertypurchase',
            options={'verbose_name': '13 My Property Purchase', 'verbose_name_plural': '13 My Property Purchase'},
        ),
        migrations.AlterModelOptions(
            name='mypropertypurchasepayment',
            options={'verbose_name': '14 My Property Purchase Payment', 'verbose_name_plural': '14 My Property Purchase Payment'},
        ),
        migrations.AlterModelOptions(
            name='mypropertypurchasepaymentstatus',
            options={'verbose_name': '16 My Property Purchase Payment Status', 'verbose_name_plural': '16 My Property Purchase Payment Status'},
        ),
        migrations.AlterModelOptions(
            name='mypropertypurchasestatus',
            options={'verbose_name': '15 My Property Purchase Status', 'verbose_name_plural': '15 My Property Purchase Status'},
        ),
        migrations.AlterModelOptions(
            name='myrenting',
            options={'verbose_name': '9 My Renting', 'verbose_name_plural': '9 My Renting'},
        ),
        migrations.AlterModelOptions(
            name='myrentingpayment',
            options={'verbose_name': '10 My Renting Payment', 'verbose_name_plural': '10 My Renting Payment'},
        ),
        migrations.AlterModelOptions(
            name='myrentingpaymentstatus',
            options={'verbose_name': '12 My Renting Payment Status', 'verbose_name_plural': '12 My Renting Payment Status'},
        ),
        migrations.AlterModelOptions(
            name='myrentingstatus',
            options={'verbose_name': '11 My Renting Status', 'verbose_name_plural': '11 My Renting Status'},
        ),
        migrations.AlterUniqueTogether(
            name='mybooking',
            unique_together={('user', 'property')},
        ),
    ]
