# Generated by Django 5.0.6 on 2024-07-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0017_alter_myaddress_options_alter_mybooking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myaddress',
            options={'verbose_name': '02. My Address', 'verbose_name_plural': '02. My Address'},
        ),
        migrations.AlterModelOptions(
            name='mybooking',
            options={'verbose_name': '05. My Booking', 'verbose_name_plural': '05. My Booking'},
        ),
        migrations.AlterModelOptions(
            name='mybookingpayment',
            options={'verbose_name': '07. Booking Payment', 'verbose_name_plural': '07. Booking Payment'},
        ),
        migrations.AlterModelOptions(
            name='mybookingpaymentstatus',
            options={'verbose_name': '08. Booking Payment Status', 'verbose_name_plural': '08. Booking Payment Status'},
        ),
        migrations.AlterModelOptions(
            name='mybookingstatus',
            options={'verbose_name': '06. Booking Status', 'verbose_name_plural': '06. Booking Status'},
        ),
        migrations.AlterModelOptions(
            name='myfavoriteproperty',
            options={'verbose_name': '01. My Favorite Property', 'verbose_name_plural': '01. My Favorite Property'},
        ),
        migrations.AlterModelOptions(
            name='mymobilemoneypaymentinfos',
            options={'verbose_name': '04. Mobile Money Payment ', 'verbose_name_plural': '04. Mobile Money Payment '},
        ),
        migrations.AlterModelOptions(
            name='mypaymentcard',
            options={'verbose_name': '03. My Payment Card', 'verbose_name_plural': '03. My Payment Card'},
        ),
        migrations.AlterModelOptions(
            name='myrenting',
            options={'verbose_name': '09. Renting', 'verbose_name_plural': '09. Renting'},
        ),
    ]
