# Generated by Django 5.0.6 on 2024-07-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0019_mybookingpaymentstatus_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypropertypurchasepaymentstatus',
            name='property_purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.mypropertypurchase'),
        ),
        migrations.AddField(
            model_name='myrentingpaymentstatus',
            name='renting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.myrenting'),
        ),
    ]
