# Generated by Django 5.0.6 on 2024-07-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0020_mypropertypurchasepaymentstatus_property_purchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myaddress',
            options={'verbose_name': '02. User Addresses', 'verbose_name_plural': '02. User Addresses'},
        ),
        migrations.AlterModelOptions(
            name='mybooking',
            options={'verbose_name': '05. User Bookings', 'verbose_name_plural': '05. User Bookings'},
        ),
        migrations.AlterModelOptions(
            name='myfavoriteproperty',
            options={'verbose_name': '01. User Favorite Properties', 'verbose_name_plural': '01. User Favorite Properties'},
        ),
        migrations.AlterModelOptions(
            name='mymobilemoneypaymentinfos',
            options={'verbose_name': '04. Mobile Money Payments ', 'verbose_name_plural': '04. Mobile Money Payments '},
        ),
        migrations.AlterModelOptions(
            name='mypaymentcard',
            options={'verbose_name': '03. Users Payment Cards', 'verbose_name_plural': '03. Users Payment Cards'},
        ),
        migrations.AlterModelOptions(
            name='mypropertypurchase',
            options={'verbose_name': '13. User Property Purchase', 'verbose_name_plural': '13. User Property Purchase'},
        ),
        migrations.AlterModelOptions(
            name='myrenting',
            options={'verbose_name': '09. User Renting', 'verbose_name_plural': '09. User Renting'},
        ),
    ]
