# Generated by Django 5.0.6 on 2024-07-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0021_alter_myaddress_options_alter_mybooking_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrentingstatus',
            old_name='canceled',
            new_name='renting_canceled',
        ),
        migrations.RenameField(
            model_name='myrentingstatus',
            old_name='completed',
            new_name='renting_confirmed',
        ),
        migrations.RenameField(
            model_name='myrentingstatus',
            old_name='confirmed',
            new_name='renting_started',
        ),
        migrations.RenameField(
            model_name='myrentingstatus',
            old_name='completed_at',
            new_name='started_at',
        ),
    ]
