# Generated by Django 5.0.6 on 2024-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0024_rename_renting_canceled_myrentingstatus_renting_request_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrentingpayment',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
