# Generated by Django 5.0.6 on 2024-07-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0025_myrentingpayment_transaction_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mybooking',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mybookingpayment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mybookingpaymentstatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mybookingstatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchasepayment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchasepaymentstatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mypropertypurchasestatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='myrenting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='myrentingpayment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='myrentingpaymentstatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='myrentingstatus',
            unique_together=set(),
        ),
    ]
