# Generated by Django 5.0.6 on 2024-07-26 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_alter_propertyrentingrequirements_options'),
        ('user_data', '0026_alter_mybooking_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrentingpayment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='myrenting',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='myrentingstatus',
            unique_together={('user', 'renting')},
        ),
    ]
