# Generated by Django 5.0.6 on 2024-07-26 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0027_alter_myrentingpayment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrentingpayment',
            name='renting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_data.myrenting'),
        ),
        migrations.AlterField(
            model_name='myrentingpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
