# Generated by Django 5.0.6 on 2024-07-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0029_alter_myrentingpayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrentingstatus',
            name='renting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_data.myrenting'),
        ),
    ]
