# Generated by Django 5.0.6 on 2024-07-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0030_alter_myrentingstatus_renting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookingpayment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_data.mybooking'),
        ),
        migrations.AlterField(
            model_name='mybookingpaymentstatus',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.mybooking'),
        ),
        migrations.AlterField(
            model_name='mybookingstatus',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_data.mybooking'),
        ),
        migrations.AlterField(
            model_name='myrentingpaymentstatus',
            name='renting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_data.myrenting'),
        ),
    ]
