# Generated by Django 5.0.7 on 2025-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0033_alter_myrentingpayment_renting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypropertypurchasepayment',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
