# Generated by Django 5.0.6 on 2024-07-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertyamenity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfacility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
