# Generated by Django 5.0.6 on 2024-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_currency_property_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='host',
        ),
        migrations.AddField(
            model_name='property',
            name='business_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('rent_sale', 'Rent/Sale'), ('booking', 'Booking')], default='rent', max_length=100),
        ),
    ]
