# Generated by Django 5.0.6 on 2024-07-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_myfavoriteproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFavoriteProperty',
        ),
    ]
