# Generated by Django 5.0.6 on 2024-07-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_propertyreview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='business_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('booking', 'Booking')], default='rent', max_length=100),
        ),
    ]
