# Generated by Django 5.0.6 on 2024-07-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_property_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedGeoRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address_code', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='business_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('booking', 'Booking')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='period',
            field=models.CharField(choices=[('night', 'Night'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10, null=True),
        ),
    ]
