# Generated by Django 5.0.6 on 2024-07-20 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_property_supported_geo_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverGeoRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address_code', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('derivery_available', models.BooleanField(default=False)),
                ('delivery_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10, null=True)),
                ('delivery_support_geo_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_support_geo_region', to='property.delivergeoregion')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_as_product', to='property.property')),
            ],
        ),
    ]
