# Generated by Django 5.0.6 on 2024-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_propertyasproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivergeoregion',
            name='region_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supportedgeoregions',
            name='region_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
