# Generated by Django 5.0.6 on 2024-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_delivergeoregion_slug_supportedgeoregions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivergeoregion',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supportedgeoregions',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
