# Generated by Django 5.0.6 on 2024-07-20 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_propertyasproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_draft', models.FileField(blank=True, null=True, upload_to='contract_draft/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_for_rent', to='property.property')),
            ],
            options={
                'verbose_name': 'Property For Rent',
                'verbose_name_plural': 'Properties For Rent',
            },
        ),
        migrations.DeleteModel(
            name='PropertyAsProduct',
        ),
    ]
