# Generated by Django 5.0.6 on 2024-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_propertybookingorrentingrules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contract_draft',
            field=models.FileField(blank=True, null=True, upload_to='contract_draft/'),
        ),
        migrations.DeleteModel(
            name='PropertyForRent',
        ),
    ]
