# Generated by Django 5.0.6 on 2024-07-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_propertyhostcancelationpolicy_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyhostcancelationpolicy',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelation_policy', to='property.property'),
        ),
    ]
