# Generated by Django 5.0.6 on 2024-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_alter_propertyhostcancelationpolicy_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyhostcancelationpolicy',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
