# Generated by Django 5.0.6 on 2024-07-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_propertyhostcancelationpolicy_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyBookingOrRentingRules',
            new_name='PropertyRules',
        ),
    ]
