# Generated by Django 5.0.6 on 2024-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_rename_propertybookingorrentingrules_propertyrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrentingrequirements',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
