# Generated by Django 5.0.6 on 2024-07-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_propertyrentingrequirements_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRentingDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('Tsh', 'Tsh'), ('USD', 'USD'), ('Ksh', 'Ksh'), ('EUR', 'EUR')], default='Tsh', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renting_duration', to='property.property')),
            ],
        ),
    ]
