# Generated by Django 5.0.6 on 2024-07-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_propertyrentingduration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyRentingDuration',
        ),
    ]
