# Generated by Django 5.0.6 on 2024-07-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_delete_propertyrentingduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRentingDurationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_number', models.IntegerField()),
                ('duration', models.CharField(choices=[('night', 'Night'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renting_duration_options', to='property.property')),
            ],
        ),
    ]
