# Generated by Django 5.0.6 on 2024-07-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_propertyrentingdurationoptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyrentingdurationoptions',
            old_name='duration',
            new_name='time_in_text',
        ),
    ]
