# Generated by Django 5.0.6 on 2024-07-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_rename_duration_propertyrentingdurationoptions_time_in_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrentingdurationoptions',
            name='time_in_text',
            field=models.CharField(choices=[('night', 'Night'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10, null=True),
        ),
    ]
