# Generated by Django 5.0.6 on 2024-07-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_data', '0001_initial'),
        ('property', '0034_alter_propertyrentingdurationoptions_time_in_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_host', to='host_data.propertyhost'),
        ),
        migrations.AlterField(
            model_name='propertyhostcancelationpolicy',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_cancelation_policy', to='host_data.propertyhost'),
        ),
        migrations.RemoveField(
            model_name='propertyhostverification',
            name='host',
        ),
        migrations.DeleteModel(
            name='Propertyhost',
        ),
        migrations.DeleteModel(
            name='PropertyHostVerification',
        ),
    ]
