# Generated by Django 5.0.6 on 2024-07-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_alter_property_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyhostcancelationpolicy',
            name='host',
        ),
        migrations.RemoveField(
            model_name='propertyhostcancelationpolicy',
            name='property',
        ),
    ]
