# Generated by Django 5.0.6 on 2024-07-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': '04. Properties', 'verbose_name_plural': '04. Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyamenity',
            options={'verbose_name': '10. Property Amenity', 'verbose_name_plural': '10. Property Amenity'},
        ),
        migrations.AlterModelOptions(
            name='propertyfacility',
            options={'verbose_name': '09. Property Facility', 'verbose_name_plural': '09. Property Facility'},
        ),
        migrations.AlterModelOptions(
            name='propertyhostcancelationpolicy',
            options={'verbose_name': '05. Cancelation Policy', 'verbose_name_plural': '05. Cancelation Policy'},
        ),
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': '08. Property Images', 'verbose_name_plural': '08. Property Images'},
        ),
        migrations.AlterModelOptions(
            name='propertyrentingdurationoptions',
            options={'verbose_name': '12. Property Renting Duration Options', 'verbose_name_plural': '12. Property Renting Duration Options'},
        ),
        migrations.AlterModelOptions(
            name='propertyrentingrequirements',
            options={'verbose_name': '07. Property Renting Requirements', 'verbose_name_plural': '07. Property Renting Requirements'},
        ),
        migrations.AlterModelOptions(
            name='propertyreview',
            options={'verbose_name': '11. Property Review', 'verbose_name_plural': '11. Property Review'},
        ),
        migrations.AlterModelOptions(
            name='propertyrules',
            options={'verbose_name': '06. Property Rules', 'verbose_name_plural': '06. Property Rules'},
        ),
    ]
