# Generated by Django 5.0.6 on 2024-07-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_alter_property_options_alter_propertyamenity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrentingdurationoptions',
            options={'verbose_name': '12. Renting Duration Options', 'verbose_name_plural': '12. Renting Duration Options'},
        ),
    ]
