# Generated by Django 5.0.6 on 2024-07-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0039_alter_propertyrentingdurationoptions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrentingrequirements',
            options={'verbose_name': '07. Renting Requirements', 'verbose_name_plural': '07. Renting Requirements'},
        ),
    ]
