# Generated by Django 5.0.6 on 2024-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_alter_propertyrentingrequirements_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedgeoregions',
            name='is_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportedgeoregions',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
