# Generated by Django 5.0.6 on 2024-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0041_supportedgeoregions_is_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedgeoregions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='geo_region_images/'),
        ),
    ]
