# Generated by Django 5.0.6 on 2024-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0043_alter_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='business_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('reserve', 'Reserve')], max_length=100, null=True),
        ),
    ]
